// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyD4_WVUjo9puhxmnqAK8H6QNYksaZkUc',
    appId: '1:565440370476:web:c1723d8aa32cf7845f3e89',
    messagingSenderId: '565440370476',
    projectId: 'express-bus-895e3',
    authDomain: 'express-bus-895e3.firebaseapp.com',
    storageBucket: 'express-bus-895e3.firebasestorage.app',
    measurementId: 'G-XVF48367N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5JME0LxECjxjKFGS-CfG5Eu4jQ0QMT1A',
    appId: '1:565440370476:android:b7e4f28a40a90b355f3e89',
    messagingSenderId: '565440370476',
    projectId: 'express-bus-895e3',
    storageBucket: 'express-bus-895e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkU4aut8mI6JF1LsfpXuGOCJWgB6ZnVpQ',
    appId: '1:565440370476:ios:73fbfdfc16c65ca25f3e89',
    messagingSenderId: '565440370476',
    projectId: 'express-bus-895e3',
    storageBucket: 'express-bus-895e3.firebasestorage.app',
    iosBundleId: 'com.example.expressAdministrator',
  );
}
